[[vmts]]
class = "NS_SPRJ::ParamResCap"
vftable = "param_res_cap_vmt"

[[vmts]]
class = "NS_SPRJ::SoloParamRepositoryImp"
vftable = "solo_param_repository_vmt"

[[patterns]]
pattern = "48 83 ec 20 48 8d 05 ${ ' } 48 8b f9 48 89 01 48 8b ca 48 8b 02 ff 50 10"
captures = ["", "fd4res_cap_vmt"]

[[patterns]]
pattern = "c6 47 60 00 48 8d 05 $ { ' } 48 89 07 33 f6 48 89 77 68 48 89 77 70 48 89 77 78"
captures = ["", "fd4param_res_cap_vmt"]

[[patterns]]
pattern = "c7 44 24 20 00 00 00 00 48 8b 05 $ { ' } 48 8b 58 08 8b 02"
captures = ["", "game_data_man_ptr"]

[[patterns]]
pattern = "48 8b ce 48 8b f8 e8 $ { 48 89 0d $ { ' } c3 }"
captures = ["", "global_hinstance"]

[[patterns]]
pattern = "e8 [4] 48 8b 0d $ { ' } 4c 8d 4c 24 60 4c 8b c7"
captures = ["", "map_item_man_ptr"]

[[patterns]]
pattern = "4c 8d 44 24 40 48 8d 54 24 50 48 8b cb e8 $ { ' }"
captures = ["", "map_item_man_grant_item"]
