[package]
name = "invoke-esd"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
eldenring.workspace = true
fromsoftware-shared.workspace = true
windows.workspace = true

[lib]
crate-type = ["cdylib"]
