[[patterns]]
pattern = "[23] 41 b8 58 00 00 00 48 8b ? ff 50 18 83 f8 58"
captures = ["equip_game_data_deserialize"]

[[patterns]]
pattern = "[20] 48 8b d9 41 b8 58 00 00 00 48 8b ? ff 50 18 48 83 f8 58"
captures = ["equip_game_data_serialize"]

[[patterns]]
pattern = "45 33 c0 89 11 85 d2 78 1d 48 63 c2 48 83 f8 2b 73 14 48 c1 e0 04 4c 8d 05 $ { ' }"
captures = ["", "gesture_data_store"]

[[patterns]]
pattern = "[16] 48 8d 6c 24 d9 48 81 ec 00 01 00 00 48 c7 45 cf fe ff ff ff"
captures = ["map_item_man_grant_item"]

[[patterns]]
pattern = "48 8b 0d $ { ' } bb [4] 41 bc"
captures = ["", "map_item_man_ptr"]

[[patterns]]
pattern = "45 33 c0 41 8d ? ? 48 83 c4 ? 5b e9 $ { ' }"
captures = ["", "register_task"]
