[package]
name = "present-action-button"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
shared.workspace = true
eldenring.workspace = true

[lib]
crate-type = ["cdylib"]
