[[offsets]]
pattern = "40 57 48 83 ec 40 48 c7 44 24 20 fe ff ff ff 48 89 5c 24 50 48 89 6c 24 58 48 89 74 24 60 49 8b f0 48 8b fa 48 8b d9 48 8d 69 28"
captures = ["CS_EZ_DRAW_DRAW_LINE"]

[[offsets]]
pattern = "48 8b c4 55 48 8d 68 88 48 81 ec 70 01 00 00 0f 29 70 e8 0f 28 35 $ {} 0f 29 78 d8"
captures = ["CS_EZ_DRAW_DRAW_CAPSULE"]

[[offsets]]
pattern = "48 8b c4 55 48 8d 68 a1 48 81 ec b0 00 00 00 0f 28 2d $ {} 0f 28 25 $ {} 0f 28 1d $ {}"
captures = ["CS_EZ_DRAW_DRAW_SPHERE"]

[[offsets]]
pattern = "f3 44 0f 11 6c 24 20 41 0f 28 df 4c 8d 45 e0 48 8d 55 90 48 8b cb e8 $ { ' }"
captures = ["", "CS_EZ_DRAW_DRAW_WEDGE"]

[[offsets]]
pattern = "0f c6 c4 e8 0f c6 d0 d4 0f 29 55 20 ? 8d 55 00 ? 8b ce e8 $ { ' }"
captures = ["", "CS_EZ_DRAW_DRAW_TRIANGLE"]

[[offsets]]
pattern = "0f 28 df ? 8d 45 07 ? 8d 55 f7 ? 8b cb e8 $ { ' }"
captures = ["", "CS_EZ_DRAW_DRAW_DODECADRON"]

[[offsets]]
pattern = "b2 08 48 8d 4d 00 e8 $ { ' }"
captures = ["", "INITIALIZE_SPAWN_GEOMETRY_REQUEST"]

[[offsets]]
pattern = "8b 01 89 85 d8 00 00 00 48 8d 55 00 49 8b ce e8 $ { ' }"
captures = ["", "SPAWN_GEOMETRY"]

[[offsets]]
pattern = "ba 58 00 00 02 e8 $ { ' }"
captures = ["", "CS_PHYS_WORLD_CAST_RAY"]

[[offsets]]
pattern = "40 53 55 56 57 48 81 ec 98 07 00 00 48 c7 44 24 50 fe ff ff ff"
captures = ["CS_BULLET_MANAGER_SPAWN_BULLET"]

[[offsets]]
pattern = "48 8b c8 45 33 c0 ba 7f 14 00 00 e8 $ { ' }"
captures = ["", "CHR_INS_APPLY_SPEFFECT"]

[[offsets]]
pattern = "ba 1c 00 00 00 48 8b ce 84 c0 74 ? e8 $ { ' } eb ?"
captures = ["", "CHR_INS_REMOVE_SPEFFECT"]

[[offsets]]
pattern = "88 44 24 28 0f b6 84 24 c0 00 00 00 88 44 24 20 e8 $ { ' }"
captures = ["", "CS_ACTION_BUTTON_MAN_EXECUTE_ACTION_BUTTON"]

[[offsets]]
pattern = "ba d0 07 00 00 48 83 c4 28 e9 $ { ' }"
captures = ["", "CS_MENU_MAN_DISPLAY_STATUS_MESSAGE"]

[[offsets]]
captures = ["", "GLOBAL_HINSTANCE"]
pattern = "48 8b ce 48 8b f8 e8 $ { 48 89 0d $ { ' } c3 }"
