[package]
name = "apply-speffect"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
fromsoftware-shared.workspace = true
eldenring.workspace = true

[lib]
crate-type = ["cdylib"]
